### ISSUE TITLE
我在我手机上演示感觉距离不对

### ISSUE THREAD

**Issue by Oliver3493000** [DakeQQ/YOLO-Depth-Drivable-Estimation-for-Android#2]
焦距那几个值啥意思，请问通过什么途径设置的值，镜头规格书？
![image](https://github.com/DakeQQ/YOLO-Depth-Drivable-Estimation-for-Android/assets/173454007/7490eb9f-3793-4eb6-b180-2a478a4a1639)

算焦距这部分确实没看懂

**Comment by Oliver3493000** [comment]
我调了半天
![image](https://github.com/DakeQQ/YOLO-Depth-Drivable-Estimation-for-Android/assets/173454007/16bd6815-1b1c-44ec-bc65-999e322d72f9)
zhi值都不对，请教下作者

**Comment by DakeQQ** [comment]
数值靠经验标定，把杯子放在距离1m的地方，中心白十字对准杯子，这时候中心距离会显示一个数值D，
D*factor = 1; 
factor = 1/D; 
依此类推，作各种距离的标定.

很不负责任地说，不准其实很正常，Demo实现方法是从“相对深度”反推近似实际距离的. 而且只用了small模型，而small模型画成深度热力图，基本就是模糊一片. 深度区分不明显.
记得DepthAnything原作者有提供"直出距离”的模型，模型尺寸挺大的不好部署，最近忙暂时没机会弄弄“直出距离”的那款.

**Comment by DakeQQ** [comment]
已更新Depth Anything V2 - Metric, 效果比之前稍微好一点点点点点点点. 若您手机算力足够的话，可以自行导出最大参数量的版本部署试试.
