### ISSUE TITLE
Inquiry About YOLOv10 on Qualcomm NPU

### ISSUE THREAD

**Issue by Plumess** [DakeQQ/YOLO-Depth-Drivable-Estimation-for-Android#3]
Hi,

I noticed that you mentioned only YOLO v9 and NAS can utilize the Qualcomm NPU (HTP), while other YOLO series models are unsupported, potentially failing to compile or crashing upon execution.

I would like to ask if you have encountered similar issues with the GatherElements operator or other validation mismatches. How did you diagnose and conclude that this issue was due to a lack of official support? If this is a complex issue requiring updates from Qualcomm and ONNX, I might need to consider using other models.

I am currently attempting to quantize the official YOLOv10 ONNX model to a Qualcomm QNN model. During this process, I encountered a warning related to the cast layer, indicating that only specific data type conversions are supported. Although there were no other significant errors during the quantization process, I faced a validation mismatch error with the GatherElements layer when running qnn-net-run.

Thank you for your time and assistance.

---

您好,

我注意到，您提到目前只有YOLO v9和NAS可以利用高通NPU（HTP），而其他YOLO系列模型不受支持，可能会在编译时失败或执行时崩溃。

我想请问您遇到的是否也是类似的GatherElements算子或其他验证不匹配的问题，您是如何定位和得出该问题是官方不支持而导致的？如果这是一个复杂的问题，需要等待高通和ONNX的更新，我可能需要考虑使用其他模型。

我目前正在尝试将官方的YOLOv10 ONNX模型量化为高通的QNN模型。在这个过程中，我遇到了一个与cast层相关的警告，该警告提示只支持特定的数据类型转换。虽然量化过程中没有其他明显的错误，但在运行qnn-net-run时，我遇到了GatherElements层验证不匹配的错误。

**Comment by DakeQQ** [comment]
Received your feedback. After a closer look, I'll get back to you. Tested on v8 and v10, no crashes during compilation (with USE_QNN) and both launched fine, with FPS similar to v9. However, the critical issue is incorrect detection outputs and scrambled inference data in v8 and v10. Preliminary speculation suggests possible compatibility issues between the Qualcomm platform and ONNX model. Further investigation into the exact cause was not pursued at the time.

已收到问题反馈, 细查看看后再回复您。我在v8和v10版本上测试时，它们在编译阶段（USE_QNN）未发生崩溃，并能正常启动，且帧率（FPS）与v9相近。但关键问题是，v8和v10的检测输出结果错误，模型推理数据混乱。初步推测这可能是高通平台与ONNX模型算子的问题，当时未深入调查具体原因。

**Comment by DakeQQ** [comment]
目前官方文档说高通HTP普遍不支持int64的数据类型, (只看到最近更新的Cast能用int64). 然而v10里面有很多使用到int64的操作，TopK，GatherElement，Div…等，应该是这样导致的输出推理结果不对. 您可以考虑一下NAS或v9了.

The official documentation currently states that Qualcomm HTP generally does not support the int64 data type (except for the recently updated Cast operation). Many operations in v10, such as TopK, GatherElement, Div, and more, rely on int64, which likely leads to incorrect inference outputs. You might want to consider NAS or v9 instead.

**Comment by Plumess** [comment]
谢谢你的指导，我也向高通QNN的官方Discord求助了，确实是GatherElement等算子的支持程度不够的原因。

Thank you for your guidance. I also sought help from Qualcomm QNN's official Discord, and it turns out that the issue is indeed due to the insufficient support for operators like GatherElement.
