### ISSUE TITLE
使用其他高通芯片跑NPU

### ISSUE THREAD

**Issue by cvv-student** [DakeQQ/YOLO-Depth-Drivable-Estimation-for-Android#4]
最近在尝试QNN跑HTP，QNN官网的文档像shit狗屁不通，你的DEMO还是挺牛的，想请问你是怎么知道需要这些运行库的，我尝试了在778G上跑HTP,拉了和你一样的库，没有跑通

**Comment by cvv-student** [comment]
主要是系统库这块

**Comment by DakeQQ** [comment]
创建QNN session时候, 
`ort_runtime_A->CreateEnv(ORT_LOGGING_LEVEL_ERROR,` "myapplication", &ort_env_A);
把`ORT_LOGGING_LEVEL_ERROR`改成`ORT_LOGGING_LEVEL_VERBOSE`, 
然后看Locat里面，QNN会说它找不到啥东西, 然后慢慢找啰~几乎都在system和vendor里面.

**Comment by DakeQQ** [comment]
恩我也觉得QNN换汤不换药，小改的SNPE
🫱✨
😊

**Comment by sushuChina** [comment]
> 牛逼，学到了，确实也在GEN1上跑起来了，但是骁龙888和778g还是有问题的，应该就是SNPE的升级版，SNPE不支持的FP16模型，QNN在同样的芯片上也不支持吧
 您好, 请问您在8Gen1平台运行的时候，是添加了哪些系统的库呢，我用作者的demo在8Gen2平台上可以运行，使用同样的步骤在8Gen1平台运行提示的如下错误https://github.com/DakeQQ/YOLO-Depth-Estimation-for-Android/issues/5#issue-2574558346。

**Comment by cvv-student** [comment]
就按照作者说法做的，基本上跟GEN2的差不多，但是项目已经删了，QNN实在运行库太大了后面没搞了，你可以先在GEN2上跑通先看看

**Comment by zylo117** [comment]
> 创建ORT session时候, `ort_runtime_A->CreateEnv(ORT_LOGGING_LEVEL_ERROR, "myapplication", &ort_env_A);` 把`ORT_LOGGING_LEVEL_ERROR`改成`ORT_LOGGING_LEVEL_VERBOSE`, 然后看Locat里面，QNN会说它找不到啥东西, 然后慢慢找啰~几乎都在system和vendor里面. 记得再改回ORT_LOGGING_LEVEL_ERROR，不然会降低推理性能!

厉害老哥，虽然文档不全，错漏了一些关键细节。但是靠verbose慢慢补全了。现在在8g4上跑通了(1.21 onnx + 2.31 qnn)，8g4要多加两个so才能跑。有点好奇除了qnn部分的那一堆so能不能跨机型和系统通用，不然认机型的话很难分发。不知道老哥这边有没有研究过呢？@DakeQQ

**Comment by cvv-student** [comment]
@zylo117 不行的，https://docs.qualcomm.com/bundle/publicresource/topics/80-63442-2/overview.html，详情见这个文档吗，不同芯片架构有几个是完全不通用的

**Comment by DakeQQ** [comment]
@zylo117 我们认知里面也是不行通用的。 。 。话说方便分享一下8Gen4的FPS速度吗？超级好奇～

**Comment by cvv-student** [comment]
@DakeQQ 在产品上，如果一个机型配置不同的so库技术上实现很麻烦，如果全部打包库又太大了，（实际使用snpe并非QNN）上次考虑到用下发解决问题，使用动态加载，但是有一个库没法动态加载可能涉及到系统权限啥的，老哥有将这东西落地到具体产品吗？或者有啥好的建议吗

**Comment by DakeQQ** [comment]
@cvv-student 
高通这玩意是闭源的我们也没有啥好解决方法。您可以考虑转换到LiteRT-QNN （原TFLite），似乎高通对他的支持度比ONNX强点。 LiteRT调用GPU也方便。 LiteRT-CPU还能支持fp16计算。最大问题就是PYTORCH模型算子转换支持度比较弱些。

手机端的话没有具体落地产品。 。 。工作都是确定的芯片型号8155/8295，不曾想过通用场景。主要是拿来处理固定输入尺寸的图像或声音小模型。

**Comment by zylo117** [comment]
> [@zylo117](https://github.com/zylo117) 我们认知里面也是不行通用的。 。 。话说方便分享一下8Gen4的FPS速度吗？超级好奇～

55到60帧，8g1+是34帧

**Comment by cvv-student** [comment]
@DakeQQ谢谢大佬了

**Comment by zylo117** [comment]
> [@zylo117](https://github.com/zylo117) 我们认知里面也是不行通用的。 。 。话说方便分享一下8Gen4的FPS速度吗？超级好奇～

实测miui14（安卓13）和澎湃1（安卓14）的8g1+在adb复制过来的so文件虽然不一样，但是是通用的（安卓14可以用安卓13的，反过来就没试过），只要qnn的so对应上芯片就行。但是adb复制过来的so也是认芯片的，直接用8g4（安卓15）的是跑不了的。
起码可以证明一件事。就是明明带上qnn的库就行了，没有必要带上系统的库。可惜安卓权限问题，要么不能读系统的库，要么系统的库太旧，你qnn和onnx的版本也要跟着系统的走，其实无论怎么做app都只能是专机专用

**Comment by zylo117** [comment]
> [@zylo117](https://github.com/zylo117) 不行的，[https://docs.qualcomm.com/bundle/publicresource/topics/80-63442-2/overview.html，详情见这个文档吗，不同芯片架构有几个是完全不通用的](https://docs.qualcomm.com/bundle/publicresource/topics/80-63442-2/overview.html%EF%BC%8C%E8%AF%A6%E6%83%85%E8%A7%81%E8%BF%99%E4%B8%AA%E6%96%87%E6%A1%A3%E5%90%97%EF%BC%8C%E4%B8%8D%E5%90%8C%E8%8A%AF%E7%89%87%E6%9E%B6%E6%9E%84%E6%9C%89%E5%87%A0%E4%B8%AA%E6%98%AF%E5%AE%8C%E5%85%A8%E4%B8%8D%E9%80%9A%E7%94%A8%E7%9A%84)

不是说qnn的库在不同机型上混用，那个肯定不行，是说adb复制过来的那些通用库混用（至少看起来通用，除了dsp那个）

**Comment by DakeQQ** [comment]
> 实测miui14（安卓13）和澎湃1（安卓14）的8g1+在adb复制过来的so文件虽然不一样，但是是通用的（安卓14可以用安卓13的，反过来就没试过），只要qnn的so对应上芯片就行。但是adb复制过来的so也是认芯片的，直接用8g4（安卓15）的是跑不了的。
起码可以证明一件事。就是明明带上qnn的库就行了，没有必要带上系统的库。可惜安卓权限问题，要么不能读系统的库，要么系统的库太旧，你qnn和onnx的版本也要跟着系统的走，其实无论怎么做app都只能是专机专用

是的勒～ 理论上只要有QNN的库 + LD_LIBRARY_PATH & ADSP_LIBRARY_PATH 指向system/lib64和vendor/lib64就行。但没有root过的会有访问权限问题

**Comment by zylo117** [comment]
> > 实测miui14（安卓13）和澎湃1（安卓14）的8g1+在adb复制过来的so文件虽然不一样，但是是通用的（安卓14可以用安卓13的，反过来就没试过），只要qnn的so对应上芯片就行。但是adb复制过来的so也是认芯片的，直接用8g4（安卓15）的是跑不了的。
> > 起码可以证明一件事。就是明明带上qnn的库就行了，没有必要带上系统的库。可惜安卓权限问题，要么不能读系统的库，要么系统的库太旧，你qnn和onnx的版本也要跟着系统的走，其实无论怎么做app都只能是专机专用
> 
> 是的勒～ 理论上只要有QNN的库 + LD_LIBRARY_PATH & ADSP_LIBRARY_PATH 指向system/lib64和vendor/lib64就行。但没有root过的会有访问权限问题

老哥有没有试过这个onnxruntime-qnn？官方发布的安卓java库，集成了qnn。不过我跑不起来，似乎链接到系统库导致版本不匹配了。https://central.sonatype.com/artifact/com.microsoft.onnxruntime/onnxruntime-android-qnn/overview
